/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

/**
 * サーバーの稼働状態を確認する
 * @summary ヘルスチェック
 */
export const HealthResponse = zod.unknown()
