/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface AssignmentGrade {
  assignmentId?: string;
  assignmentTitle?: string;
  score?: number;
  maxScore?: number;
  submitted?: boolean;
  returned?: boolean;
}
