/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { StudentGradeResponse } from "./studentGradeResponse";

export interface CourseGradeResponse {
  courseId?: string;
  courseName?: string;
  grades?: StudentGradeResponse[];
}
