/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CreateAssignmentRequestSubmissionType = typeof CreateAssignmentRequestSubmissionType[keyof typeof CreateAssignmentRequestSubmissionType];


export const CreateAssignmentRequestSubmissionType = {
  CODE: 'CODE',
  FILE: 'FILE',
  REPORT: 'REPORT',
} as const;
