/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreateAssignmentRequestSubmissionType } from "./createAssignmentRequestSubmissionType";

export interface CreateAssignmentRequest {
  title: string;
  description?: string;
  submissionType: CreateAssignmentRequestSubmissionType;
  isPublished?: boolean;
  publishAt?: string;
  deadlineAt: string;
  maxScore?: number;
  languages?: string[];
}
