/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface EnrollmentResponse {
  id?: string;
  userId?: string;
  userName?: string;
  userEmail?: string;
  role?: string;
  enrolledAt?: string;
}
