/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface FeedbackResponse {
  id?: string;
  submissionId?: string;
  authorId?: string;
  authorName?: string;
  startLine?: number;
  endLine?: number;
  body?: string;
  createdAt?: string;
}
