/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RegisterRequest {
  email: string;
  name: string;
  /**
     * @minLength 8
     * @maxLength 2147483647
     */
  password: string;
}
