/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AssignmentGrade } from './assignmentGrade';

export interface StudentGradeResponse {
  studentId?: string;
  studentName?: string;
  studentEmail?: string;
  assignmentGrades?: AssignmentGrade[];
  totalScore?: number;
  maxTotalScore?: number;
}
