/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { JudgeResultResponse } from './judgeResultResponse';

export interface SubmissionResponse {
  id?: string;
  assignmentId?: string;
  assignmentTitle?: string;
  userId?: string;
  userName?: string;
  language?: string;
  codeContent?: string;
  fileUrl?: string;
  reportContent?: string;
  submittedAt?: string;
  returnedAt?: string;
  score?: number;
  judgeResults?: JudgeResultResponse[];
  returned?: boolean;
}
