/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TestCaseResponse {
  id?: string;
  assignmentId?: string;
  input?: string;
  expectedOutput?: string;
  score?: number;
  orderIndex?: number;
}
