/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UpdateAssignmentRequestSubmissionType } from "./updateAssignmentRequestSubmissionType";

export interface UpdateAssignmentRequest {
  title?: string;
  description?: string;
  submissionType?: UpdateAssignmentRequestSubmissionType;
  isPublished?: boolean;
  publishAt?: string;
  deadlineAt?: string;
  maxScore?: number;
  languages?: string[];
}
