/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UpdateEnrollmentRoleRequestRole = typeof UpdateEnrollmentRoleRequestRole[keyof typeof UpdateEnrollmentRoleRequestRole];


export const UpdateEnrollmentRoleRequestRole = {
  TEACHER: 'TEACHER',
  TA: 'TA',
  STUDENT: 'STUDENT',
} as const;
