/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UpdateAssignmentRequestSubmissionType =
  (typeof UpdateAssignmentRequestSubmissionType)[keyof typeof UpdateAssignmentRequestSubmissionType];

export const UpdateAssignmentRequestSubmissionType = {
  CODE: "CODE",
  FILE: "FILE",
  REPORT: "REPORT",
} as const;
