/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserResponse {
  id?: string;
  email?: string;
  name?: string;
  role?: string;
  emailVerified?: boolean;
  totpEnabled?: boolean;
  createdAt?: string;
}
